### ISSUE TITLE
I don't understand how to use the plugin

### ISSUE THREAD

**Issue by Gakhramanzode** [jenkinsci/database-postgresql-plugin#87]
### Describe your use-case which is not covered by existing documentation.

I went to **Dashboard->Manage Jenkins->Configure System**. Next, in the **Global Database** section, I entered the parameters for connecting to the Postgres database. I pressed **Test Connection** to make sure everything was in order. And what's next? How do I use this connection in my task?
<img width="814" alt="image" src="https://user-images.githubusercontent.com/62985982/226541354-83278887-60ab-46ef-ae33-17ece52cdc2c.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/62985982/226541482-20ab6dc9-5e4e-49d7-b251-32aa65b1f565.png">
![image](https://user-images.githubusercontent.com/62985982/226541533-9f159e73-66db-4896-99d6-111eeb20330a.png)
![image](https://user-images.githubusercontent.com/62985982/226541602-700bc42a-f6b0-41a5-b141-d45df76ee151.png)

**Comment by timja** [comment]
This plugin is a driver plugin for the database plugin.

See it's docs:
https://github.com/jenkinsci/database-plugin#database-plugin
